# Generated by Django 3.2.8 on 2021-11-20 15:49

import clubs.Validators.MembershipTypeValidator
import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_membershiptype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='type',
            field=models.CharField(max_length=20, validators=[clubs.Validators.MembershipTypeValidator.validate_membership_type, clubs.models.validate_club_owner]),
        ),
    ]
