# Generated by Django 3.2.8 on 2021-11-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_membershiptype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
