# Generated by Django 3.2.8 on 2021-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_membershiptype_club'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershiptype',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique membership'),
        ),
    ]
