# Generated by Django 3.2.8 on 2021-11-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_membershiptype_unique membership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershiptype',
            name='unique membership',
        ),
    ]
