# Generated by Django 3.2.8 on 2021-11-30 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_rename_user_club_club_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=190)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(96), django.core.validators.MinValueValidator(2)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('co_organising_officers', models.ManyToManyField(blank=True, related_name='_clubs_tournament_co_organising_officers_+', to=settings.AUTH_USER_MODEL)),
                ('organising_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organising officer+', to=settings.AUTH_USER_MODEL)),
                ('participating_players', models.ManyToManyField(related_name='_clubs_tournament_participating_players_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
