# Generated by Django 3.2.8 on 2021-11-30 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='deadline_to_apply',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
