# Generated by Django 3.2.8 on 2021-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_tournament_deadline_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
