# Generated by Django 3.2.8 on 2021-12-07 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_tournament_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player1', models.ManyToManyField(related_name='_clubs_match_player1_+', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ManyToManyField(related_name='_clubs_match_player2_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
