# Generated by Django 3.2.8 on 2021-12-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_clubs_tournament_matches_+', to='clubs.Match'),
        ),
    ]
