# Generated by Django 3.2.8 on 2021-12-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_alter_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
    ]
