# Generated by Django 3.2.8 on 2021-12-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_auto_20211207_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player1', to='clubs.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Player2', to='clubs.user'),
            preserve_default=False,
        ),
    ]
