# Generated by Django 3.2.8 on 2021-12-07 22:49

import clubs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20211207_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[clubs.models.validate_scores])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match+', to='clubs.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
