# Generated by Django 3.2.8 on 2021-12-09 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament')),
                ('matches', models.ManyToManyField(related_name='_clubs_round_matches_+', to='clubs.Match')),
                ('nextRound', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='next round+', to='clubs.round')),
                ('players', models.ManyToManyField(related_name='_clubs_round_players_+', to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(related_name='_clubs_round_winners_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clubs.round',),
        ),
    ]
