# Generated by Django 3.2.8 on 2021-12-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_group_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='nextRound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='next round+', to='clubs.round'),
        ),
    ]
