# Generated by Django 3.2.5 on 2021-12-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_alter_round_nextround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
