# Generated by Django 3.2.5 on 2021-12-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_score_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament'),
        ),
    ]
