# Generated by Django 3.2.5 on 2021-12-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_alter_score_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='tournament',
        ),
        migrations.AddField(
            model_name='score',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.round'),
        ),
    ]
