# Generated by Django 3.2.8 on 2021-12-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0034_auto_20211209_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_ongoing',
            field=models.BooleanField(null=True),
        ),
    ]
