# Generated by Django 3.2.8 on 2021-12-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_round_is_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
