# Generated by Django 3.2.8 on 2021-12-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0036_alter_round_is_ongoing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='is_ongoing',
            new_name='has_started',
        ),
    ]
