# Generated by Django 3.2.8 on 2021-12-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_rename_is_ongoing_round_has_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='nextRound',
        ),
    ]
