# Generated by Django 3.2.8 on 2021-12-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
