# Generated by Django 3.2.8 on 2021-12-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_alter_membershiptype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
