# Generated by Django 3.2.8 on 2021-12-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_alter_membershiptype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
